### ISSUE TITLE
エンドポイントおよびレスポンス変更のお知らせ

### ISSUE THREAD

**Issue by efumaxay** [sasairc/lsoac#1]
いつも「おさむん家 Advent Calendar 未放送記事取得API」をご利用いただきありがとうございます。

この度Firebase Cloud FunctionsからGoogle Apps Scriptへシステムを移行することになり、エンドポイントおよびレスポンスが変更となります。

![20180214222034](https://user-images.githubusercontent.com/44358526/48302741-c5dd8a00-e543-11e8-9481-41420000f418.jpg)

## 新APIエンドポイント

* <https://script.google.com/macros/s/AKfycbzNeGkemsTOvDs80HnIvNRx_PYq9Sh58BA9dSur_iLbjZNTVuY/exec>

一度Googleがリクエストをリダイレクトするため、対応したクライアントが必要です

## 新APIレスポンス

```ts
interface IPost {
  author: string;
  date: string;
  day: number;
  title: string;
  url: string;
}

interface IGetUnreadPostsApiResponse {
  posts: IPost[];
}
```

* 新APIでは予約中および空白を含む、期間中すべての記事情報が返却されます
  * `IPost.url === ''` でフィルターすることで、旧APIと同じ挙動を実現できます
* 記事構造を格納するフィールドが `result` から `posts` へ変更されます
* 記事構造へ新たに `date` フィールドが追加されました
  * このフィールドは将来的に `utcDate` へ改称される予定です

## 例

```console
$ curl -sL https://script.google.com/macros/s/AKfycbzNeGkemsTOvDs80HnIvNRx_PYq9Sh58BA9dSur_iLbjZNTVuY/exec | jq .
{
  "posts": [
    {
      "author": "sasairc",
      "date": "2018-11-04T15:00:00.000Z",
      "day": 1429,
      "title": "アングル: 米中間選挙、金融市場への波及シナリオ",
      "url": "https://gist.github.com/sasairc/0ff35283e4b47f5b446367505fb833e2"
    },
    {
      "author": "sasairc",
      "date": "2018-11-05T15:00:00.000Z",
      "day": 1430,
      "title": "テキストファイルの行と文字を全反転する",
      "url": "https://gist.github.com/sasairc/20d99b27f72b308be34242f098864804"
    },
    {
      "author": "",
      "date": "2018-11-06T15:00:00.000Z",
      "day": 1431,
      "title": "",
      "url": ""
    },
    {
      "author": "",
      "date": "2018-11-07T15:00:00.000Z",
      "day": 1432,
      "title": "",
      "url": ""
    },
    {
      "author": "",
      "date": "2018-11-08T15:00:00.000Z",
      "day": 1433,
      "title": "",
      "url": ""
    },
    {
      "author": "",
      "date": "2018-11-09T15:00:00.000Z",
      "day": 1434,
      "title": "",
      "url": ""
    },
    {
      "author": "",
      "date": "2018-11-10T15:00:00.000Z",
      "day": 1435,
      "title": "",
      "url": ""
    }
  ]
}
```

## ソースコード

<https://github.com/osm-tc159/advent/blob/master/src/index.ts#L56>

**Comment by sasairc** [comment]
@efumaxay 
![tumblr_p51i17emc71tanofjo1_540](https://user-images.githubusercontent.com/9349287/48307613-ef260680-e593-11e8-9f7c-3fa44fe52f6c.gif)

私はそれを読み、理解しました。

近いうちに wip ブランチを切り対応しますので、暫しお待ち下さい。

**Comment by sasairc** [comment]
![20171209031115b10](https://user-images.githubusercontent.com/9349287/48307736-a459be00-e596-11e8-84ba-0780a8471835.jpg)

ので本 issue をクローズします。
